name: solo_runner_flutter
description: A new Flutter project for Solo Runner.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  geolocator: ^10.1.0 # For GPS
  supabase_flutter: ^2.0.0 # Cloud DB
  flutter_tts: ^3.8.3 # Voice Coaching
  shared_preferences: ^2.2.2 # For local storage
  http: ^1.1.0 # For AI API
  google_generative_ai: ^0.2.2 # Gemini AI
  fl_chart: ^0.65.0 # For charts
  url_launcher: ^6.2.4 # For opening links
  permission_handler: ^11.3.1
  flutter_naver_map: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
